"""Change Integer to datetime

Revision ID: 333cd59796c0
Revises: e67cdbcc895c
Create Date: 2023-12-13 22:31:56.051560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333cd59796c0'
down_revision = 'e67cdbcc895c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
