"""Changed RFID column to nullable integer.

Revision ID: 62e52f69fd1c
Revises: 333cd59796c0
Create Date: 2023-12-14 18:59:40.092297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e52f69fd1c'
down_revision = '333cd59796c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('rfid',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('rfid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
